# Generated by Django 3.2.8 on 2021-10-14 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='drawing',
            table='drawing',
        ),
    ]
